name: ribotranspred
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
dependencies:
  - python=3.9.18
  - pytorch=2.1.2=py3.9_cuda12.1_cudnn8.9.2_0
  - pytorch-lightning
  - cudatoolkit
  - cudnn
  - pandas
  - numpy
  - scipy
  - pybigwig
  - kipoiseq
  - pyfaidx
  - einops
  - transformers
  - torchmetrics=0.17.0
  - matplotlib
  - seaborn
  - tqdm
  - biopython
  - h5py
  - numexpr
  - samtools
  - deeptools
  - pip
