batch_size: 4
dropout: 0.3
grad_accum: 3
learning_rate: 1.0e-05
model_type: PosTransModelTCNFiLMRef
nBins: 3000
nosequence: false
num_tissues: 9
region_len: 6000
seed: 4
tissue_emb_dim: 64
tissue_vocab:
  brain: 0
  esc_neu: 1
  heart: 2
  ipsc_cm: 3
  kidney: 4
  liver: 5
  prekidney: 6
  preliver: 7
  testis: 8
warmup_steps: 2000
weight_decay: 0.0005
